spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springbootdb
    username: postgres
    password: pass123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    show-sql: true